import { expect, test } from "@playwright/test";
import { clinicDate } from "../../lib/clinic";

test("registro, calendario, persistencia, reprogramación y cancelación", async ({ page }) => {
  const document = String(Date.now());
  await page.goto("/");
  await page.getByRole("button", { name: /Registrar paciente/ }).click();
  await page.getByRole("button", { name: "Registrarme y continuar" }).click();
  await expect(page.locator(".error-banner")).toContainText("Revise los campos");
  await page.getByLabel("Número de documento", { exact: true }).fill(document);
  await page.getByLabel("Nombres", { exact: true }).fill("Paciente Prueba");
  await page.getByLabel("Apellidos", { exact: true }).fill("Automatizada");
  await page.getByLabel("Fecha de nacimiento").fill("1990-05-20");
  await page.getByLabel("Teléfono").fill("3001234567");
  await page.getByLabel("Correo electrónico").fill("prueba@example.com");
  await page.getByLabel("Contraseña").fill("PruebaSegura123");
  await page.getByRole("button", { name: "Registrarme y continuar" }).click();
  await page.getByRole("button", { name: "Medicina General", exact: true }).click();
  await page.getByRole("button", { name: /Cualquier profesional/ }).click();
  await expect(page.getByRole("button", { name: "Continuar", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Mes siguiente" }).click();
  await page.locator(".date-button:not(:disabled)").first().click();
  await page.locator(".time-slot:not(:disabled)").first().click();
  await page.getByRole("button", { name: "Continuar", exact: true }).click();
  await expect(page.locator(".summary-card")).toContainText("Paciente Prueba Automatizada");
  await page.getByRole("button", { name: "Confirmar cita", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Tu cita fue agendada correctamente" })).toBeVisible();
  const code = await page.locator(".summary-header p").innerText();
  await page.reload();
  await page.getByRole("button", { name: "Citas", exact: true }).click();
  await page.locator(".appointment-list button").filter({ hasText: code.replace("Código de cita: ", "") }).click();
  await page.getByRole("button", { name: "Confirmar asistencia" }).click();
  await expect(page.locator(".summary-card")).toContainText("CONFIRMADA");
  await page.getByRole("button", { name: "Reprogramar", exact: true }).click();
  await page.locator(".date-button:not(:disabled)").nth(1).click();
  await page.locator(".time-slot:not(:disabled)").last().click();
  await page.getByRole("button", { name: "Continuar", exact: true }).click();
  await page.getByRole("button", { name: "Guardar reprogramación" }).click();
  await expect(page.locator(".summary-header p")).toHaveText(code);
  await page.getByRole("button", { name: "Ver mis citas" }).click();
  await page.locator(".appointment-list button").first().click();
  await page.getByRole("button", { name: "Cancelar cita", exact: true }).click();
  await page.getByRole("button", { name: "Conservar cita" }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await page.getByRole("button", { name: "Cancelar cita", exact: true }).click();
  await page.getByRole("button", { name: "Confirmar cancelación" }).click();
  await expect(page.locator(".summary-card")).toContainText("CANCELADA");
  await expect(page.getByRole("button", { name: "Reprogramar", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Mi cuenta", exact: true }).first().click();
  await page.getByRole("button", { name: "Cerrar sesión" }).click();
  await page.getByRole("button", { name: "Citas", exact: true }).click();
  await page.getByLabel("Número de documento", { exact: true }).fill(document);
  await page.getByLabel("Contraseña").fill("ContraseñaErronea");
  await page.getByRole("button", { name: "Continuar", exact: true }).click();
  await expect(page.locator(".error-banner")).toContainText("incorrectos");
  await page.getByLabel("Contraseña").fill("PruebaSegura123");
  await page.getByRole("button", { name: "Continuar", exact: true }).click();
  await expect(page.locator(".appointment-list")).toContainText("CANCELADA");
});

test("API protege datos, valida y evita doble reserva simultánea", async ({ playwright }) => {
  const first = await playwright.request.newContext({ baseURL: "http://127.0.0.1:3100", extraHTTPHeaders: { Origin: "http://127.0.0.1:3100" } });
  const second = await playwright.request.newContext({ baseURL: "http://127.0.0.1:3100", extraHTTPHeaders: { Origin: "http://127.0.0.1:3100" } });
  try {
    const values = { action: "register", documentType: "CC", documentNumber: `${Date.now()}1`, firstName: "Prueba", lastName: "API", password: "PruebaSegura123", birthDate: "1990-01-01", phone: "3001234567", email: "api@example.com" };
    expect((await first.post("/api/portal", { data: { action: "book" } })).status()).toBe(401);
    expect((await first.post("/api/portal", { data: null })).status()).toBe(400);
    expect((await first.post("/api/portal", { data: values, headers: { Origin: "https://otro.example" } })).status()).toBe(403);
    expect((await first.post("/api/portal", { data: values })).status()).toBe(200);
    expect((await first.post("/api/portal", { data: values })).status()).toBe(409);
    expect((await second.post("/api/portal", { data: { ...values, documentNumber: `${Date.now()}2` } })).status()).toBe(200);
    const future = new Date(Date.now() + 60 * 86400000);
    while ([0, 6].includes(new Date(`${clinicDate(future)}T12:00:00Z`).getUTCDay())) future.setDate(future.getDate() + 1);
    const data = { action: "book", specialty: "Cardiología", doctorId: "cardiologia-1", date: clinicDate(future), time: "10:00" };
    const results = await Promise.all([first.post("/api/portal", { data }), second.post("/api/portal", { data })]);
    expect(results.map(r => r.status()).sort()).toEqual([200, 409]);
    const winner = results[0].ok() ? first : second;
    const other = winner === first ? second : first;
    const appointment = (await results.find(r => r.ok())!.json()).data;
    expect((await other.post("/api/portal", { data: { action: "cancel", id: appointment.id } })).status()).toBe(404);
    expect((await first.post("/api/portal", { data: { ...data, date: "2020-01-01" } })).status()).toBe(409);
    expect((await winner.post("/api/portal", { data: { action: "cancel", id: appointment.id } })).status()).toBe(200);
    const replacement = await other.post("/api/portal", { data });
    expect(replacement.status()).toBe(200);
    await other.post("/api/portal", { data: { action: "cancel", id: (await replacement.json()).data.id } });
  } finally { await first.dispose(); await second.dispose(); }
});
